version: "3.8"
services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - static-data-nginx:/srv/public
    ports:
      - 80:80
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true

volumes:
  static-data-nginx:
